version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vadidb
      POSTGRES_USER: vadiadmin
      POSTGRES_PASSWORD: vadi2025!qazwsx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 